name = "pokemon-team-planner"
workers_dev = true
compatibility_date = "2025-03-11"
main = "workers-site/index.js"

[site]
bucket = "./"

[build]
command = "npm install && npm run build"

[site.static]
include = ["**/*"]
exclude = ["node_modules/**/*", ".git/**/*"]